import { Inter } from "next/font/google";
import "./globals.css";
import AuthSession from "@/util/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NEXTJS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><AuthSession>{children}</AuthSession></body>
    </html>
  );
}
