import { Inter } from "next/font/google";
import "./globals.css";
import AuthSession from "@/util/session";
import Script from "next/script";
const KAKAO_SDK_URL = `//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_APP_JS_KEY}&autoload=false&libraries=services`;

export const metadata = {
  title: "NEXTJS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body >
      <Script src={KAKAO_SDK_URL} strategy="beforeInteractive" />
      <AuthSession>{children}</AuthSession></body>
    </html>
    
  );
}
